FROM thyrlian/android-sdk

# ENV SDKROOT /work
# WORKDIR ${SDKROOT}

# # Download Flutter SDK
# RUN git clone https://github.com/flutter/flutter.git -b stable
# ENV PATH "$PATH:${SDKROOT}/flutter/bin"

# # Run basic check to download Dark SDK
# RUN flutter doctor
